function H_MAGY = calcH_MAGY(magD,magE,magN,q0,q1,q2,q3)
%CALCH_MAGY
%    H_MAGY = CALCH_MAGY(MAGD,MAGE,MAGN,Q0,Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    06-Mar-2016 06:39:18

t2 = q0.^2;
t3 = q1.^2;
t4 = q2.^2;
t5 = q3.^2;
t6 = q0.*q2.*2.0;
t7 = q1.*q3.*2.0;
t8 = q0.*q3.*2.0;
t9 = q1.*q2.*2.0;
t10 = q0.*q1.*2.0;
H_MAGY = [magN.*(t6+t7)+magD.*(t2-t3-t4+t5)-magE.*(t10-q2.*q3.*2.0),0.0,-magE.*(t8+t9)+magD.*(t6-t7)-magN.*(t2+t3-t4-t5),0.0,0.0,0.0,0.0,0.0,0.0,-t8+t9,t2-t3+t4-t5,t10+q2.*q3.*2.0,0.0,1.0,0.0];
