function H_MAGX = calcH_MAGX(magD,magE,magN,q0,q1,q2,q3)
%CALCH_MAGX
%    H_MAGX = CALCH_MAGX(MAGD,MAGE,MAGN,Q0,Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 5.8.
%    29-Dec-2014 07:01:32

t2 = q0.^2;
t3 = q1.^2;
t4 = q2.^2;
t5 = q3.^2;
t6 = q0.*q1.*2.0;
t7 = q0.*q3.*2.0;
t8 = q0.*q2.*2.0;
t9 = q1.*q3.*2.0;
H_MAGX = [0.0,-magN.*(t8+t9)-magD.*(t2-t3-t4+t5)+magE.*(t6-q2.*q3.*2.0),magE.*(t2-t3+t4-t5)+magD.*(t6+q2.*q3.*2.0)-magN.*(t7-q1.*q2.*2.0),0.0,0.0,0.0,0.0,0.0,0.0,t2+t3-t4-t5,t7+q1.*q2.*2.0,-t8+t9,1.0,0.0,0.0];
