function H_MAGZ = calcH_MAGZ(magD,magE,magN,q0,q1,q2,q3)
%CALCH_MAGZ
%    H_MAGZ = CALCH_MAGZ(MAGD,MAGE,MAGN,Q0,Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    06-Mar-2016 06:39:18

t2 = q0.^2;
t3 = q1.^2;
t4 = q2.^2;
t5 = q3.^2;
t6 = q0.*q3.*2.0;
t7 = q0.*q2.*2.0;
t8 = q0.*q1.*2.0;
t9 = q2.*q3.*2.0;
H_MAGZ = [-magD.*(t8+t9)-magE.*(t2-t3+t4-t5)+magN.*(t6-q1.*q2.*2.0),magN.*(t2+t3-t4-t5)+magE.*(t6+q1.*q2.*2.0)-magD.*(t7-q1.*q3.*2.0),0.0,0.0,0.0,0.0,0.0,0.0,0.0,t7+q1.*q3.*2.0,-t8+t9,t2-t3-t4+t5,0.0,0.0,1.0];
