function K_OPT = calcK_OPT(Popt,R_LOS,navPosD,q0,q1,q2,q3,terrainState,vel_x,vel_y,vel_z)
%CALCK_OPT
%    K_OPT = CALCK_OPT(POPT,R_LOS,NAVPOSD,Q0,Q1,Q2,Q3,TERRAINSTATE,VEL_X,VEL_Y,VEL_Z)

%    This function was generated by the Symbolic Math Toolbox version 5.8.
%    05-Jan-2015 13:37:33

t3 = q0.^2;
t4 = q1.^2;
t5 = q2.^2;
t6 = q3.^2;
t9 = t3-t4+t5-t6;
t10 = t9.*vel_y;
t11 = q0.*q3.*2.0;
t12 = q1.*q2.*2.0;
t13 = t11-t12;
t14 = t13.*vel_x;
t15 = q0.*q1.*2.0;
t16 = q2.*q3.*2.0;
t17 = t15+t16;
t18 = t17.*vel_z;
t2 = t10-t14+t18;
t7 = t3-t4-t5+t6;
t8 = navPosD-terrainState;
t19 = 1.0./t8.^4;
t23 = t3+t4-t5-t6;
t24 = t23.*vel_x;
t25 = t11+t12;
t26 = t25.*vel_y;
t27 = q0.*q2.*2.0;
t28 = q1.*q3.*2.0;
t29 = t27-t28;
t30 = t29.*vel_z;
t20 = t24+t26-t30;
t21 = t7.^2;
t22 = 1.0./t8.^2;
K_OPT = [-(Popt.*t2.*t7.*t22)./(R_LOS+Popt.*t2.^2.*t19.*t21),(Popt.*t7.*t20.*t22)./(R_LOS+Popt.*t19.*t20.^2.*t21)];
