function H_RNG = calcH_RNG(q0,q1,q2,q3)
%CALCH_RNG
%    H_RNG = CALCH_RNG(Q0,Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 5.8.
%    05-Jan-2015 13:37:33

H_RNG = reshape([1.0./(q0.^2-q1.^2-q2.^2+q3.^2)],[1, 1]);
