function K_RNG = calcK_RNG(Popt,R_RNG,q0,q1,q2,q3)
%CALCK_RNG
%    K_RNG = CALCK_RNG(POPT,R_RNG,Q0,Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 5.8.
%    05-Jan-2015 13:37:33

t2 = q0.^2;
t3 = q1.^2;
t4 = q2.^2;
t5 = q3.^2;
t6 = t2-t3-t4+t5;
K_RNG = Popt./(t6.*(R_RNG+Popt.*1.0./t6.^2));
