function H_MAG = calcH_MAG(magX,magY,magZ,q0,q1,q2,q3)
%CALCH_MAG
%    H_MAG = CALCH_MAG(MAGX,MAGY,MAGZ,Q0,Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    06-Mar-2016 06:53:35

t2 = q0.^2;
t3 = q1.^2;
t4 = q2.^2;
t5 = q3.^2;
t6 = q0.*q3.*2.0;
t8 = t2-t3+t4-t5;
t9 = q0.*q1.*2.0;
t10 = q2.*q3.*2.0;
t11 = t9-t10;
t14 = q1.*q2.*2.0;
t21 = magY.*t8;
t22 = t6+t14;
t23 = magX.*t22;
t24 = magZ.*t11;
t7 = t21+t23-t24;
t12 = t2+t3-t4-t5;
t13 = magX.*t12;
t15 = q0.*q2.*2.0;
t16 = q1.*q3.*2.0;
t17 = t15+t16;
t18 = magZ.*t17;
t19 = t6-t14;
t25 = magY.*t19;
t20 = t13+t18-t25;
t26 = 1.0./t20.^2;
t27 = t7.^2;
t28 = t26.*t27;
t29 = t28+1.0;
t30 = 1.0./t29;
t31 = 1.0./t20;
H_MAG = [-t30.*(t31.*(magZ.*t8+magY.*t11)+t7.*t26.*(magY.*t17+magZ.*t19)),t30.*(t31.*(magX.*t11+magZ.*t22)-t7.*t26.*(magZ.*t12-magX.*t17)),t30.*(t31.*(magX.*t8-magY.*t22)+t7.*t26.*(magY.*t12+magX.*t19)),0.0,0.0,0.0,0.0,0.0,0.0];
