figure;
subplot(3,1,1);
plot(ATT.data(:,2)*0.001,ATT.data(:,3),'g');
hold on;
plot(EKF.data(:,2)*0.001,EKF.data(:,3),'b');
hold off;
grid on;
xlabel('time (sec)');ylabel('roll (deg)');
subplot(3,1,2);
plot(ATT.data(:,2)*0.001,ATT.data(:,4),'g');
hold on;
plot(EKF.data(:,2)*0.001,EKF.data(:,4),'b');
hold off;
grid on;
xlabel('time (sec)');ylabel('pitch (deg)');
subplot(3,1,3);
plot(ATT.data(:,2)*0.001,ATT.data(:,5),'g');
hold on;
plot(EKF.data(:,2)*0.001,EKF.data(:,5),'b');
hold off;
grid on;
xlabel('time (sec)');ylabel('yaw (deg)');
