function H_RNG = calcH_rng(bcn_pos_d,bcn_pos_e,bcn_pos_n,veh_pos_d,veh_pos_e,veh_pos_n)
%CALCH_RNG
%    H_RNG = CALCH_RNG(BCN_POS_D,BCN_POS_E,BCN_POS_N,VEH_POS_D,VEH_POS_E,VEH_POS_N)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    02-Nov-2016 12:43:19

t2 = bcn_pos_d-veh_pos_d;
t3 = bcn_pos_e-veh_pos_e;
t4 = bcn_pos_n-veh_pos_n;
t5 = t2.^2;
t6 = t3.^2;
t7 = t4.^2;
t8 = t5+t6+t7;
t9 = 1.0./sqrt(t8);
H_RNG = [t9.*(bcn_pos_n.*2.0-veh_pos_n.*2.0).*(-1.0./2.0),t9.*(bcn_pos_e.*2.0-veh_pos_e.*2.0).*(-1.0./2.0),t9.*(bcn_pos_d.*2.0-veh_pos_d.*2.0).*(-1.0./2.0)];
